### PR TITLE
Use targetBranch when running in a Azure DevOps Pipeline

### PR DESCRIPTION
**Pull request by MartinDemberger**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Fixes Bug #1102 

### :arrow_heading_down: What is the current behavior?

Currently the targetBranch parameter isn't used when running in a Azure DevOps Pipeline.

### :new: What is the new behavior (if this is a feature change)?

Now the parameter is used.

### :thinking: Checklist before submitting

- [x] All projects build
- [ ] Relevant documentation was updated

### CODE REVIEW

**Comment by MartinDemberger** [comment]
In CreateSettingsFromRemote the targetBranch isn't used. Is this correct?

**Comment by kwlin** [comment]
Isn't this the same fix as #1078 ?

**Comment by MartinDemberger** [comment]
> Isn't this the same fix as #1078 ?

No it isn't. In #1078 is the targetbranch for `CreateSettingsFromRemote` and in this one for `CreateSettingsFromLocal` which is used in my Azure Build Pipeline.

**Comment by thijsk** [comment]
Just ran into this issue, is there anyone still working on this?

**Comment by MartinDemberger** [comment]
I'm not sure if NuKeeper is still alive. I have created my own version in my private repository with the needed changes.

**Comment by msallin** [comment]
@MartinDemberger can you please rebase the branch on the latest master. Ty!

**Comment by MartinDemberger** [comment]
> 
> 
> @MartinDemberger can you please rebase the branch on the latest master. Ty!

@msallin @I did the rebase but am unsure if it's done correct. There are changes in the changeset which I don't know.

You can give me a short hint if I have done an error. Then I will redo the changes on a clean branch.

**Comment by skolima** [comment]
@MartinDemberger I'm afraid something went wrong with the rebase - your changes were quite clean 3-4 lines, and this has about 30 extra commits. Could you re-do this so that the PR diff only shows your changes?

**Comment by MartinDemberger** [comment]
I have recreated this PR as #1139 1139

**Pull request closed without merging**
