### PR TITLE
Feature: Optional Git cmd support

### PR DESCRIPTION
**Pull request by sharpSteff**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
No git cmd support

### :new: What is the new behavior (if this is a feature change)?
optional git cmd instead of Lib2GitSharp 

### :boom: Does this PR introduce a breaking change?
should not, since its an additional feature

### :bug: Recommendations for testing
Maybe provide a git cmd resource for unit testing.

All unit tests which does git interactions should also use the GitCmdDriver as IGitDriver

### :memo: Links to relevant issues/docs
#799 

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Relevant documentation was updated

### CODE REVIEW

**Comment by MarcBruins** [comment]
Cool! @skolima worked on this before and i think there where some issues he encountered

**Comment by sharpSteff** [comment]
I tested it on gitea and GitHub. I think the biggest benifit of this Feature is, that you can rely on your already working.gitconfig in case of special stuff like proxy.

Do you have any Idea how you run unittests for this?

**Comment by skolima** [comment]
#659 was extremely unreliable and I gave up - the unpredictability of this approach was not worth the gain (even though I have huge repositories where doing a shallow clone would be a huge speedup). There's little in terms of test coverage, though, so for the spike I was relying on running this by hand for various repositories. In order to be able to merge this, you'd need to write the tests as well (current NuKeeper libgit integration is lacking them - not ideal).

**Comment by sharpSteff** [comment]
@skolima thanks for the Feedback. I see this Feature as a fallback solution in case lib2git does not the job. any ideas how to get git cmd running on build servers?

**Comment by skolima** [comment]
What I've tried doing before was checking if %PATH% actually contains git already - this would be the most common situation, I think. If not, then the build definition would need to be changed to install it.

**Comment by MarcBruins** [comment]
Two things i noticed is that the GitDiscoveryDriver isn't updated and there are no docs update with this PR.

**Comment by sharpSteff** [comment]
Will fix that tomorrow

**Comment by skolima** [comment]
In `StartGitProzess` (typo!) you've got your own `Process` handling. This should be using `ExternalProcess` as other places that launch executables from NuKeeper do. 2 reasons for this: a ) consistency b) if there's *any* bugs in `ExternalProcess`, those are rather critical to how NuKeeper works, so, we need to fix them. And if this works, then definitely the logging support should be used here as well.

**Comment by skolima** [comment]
`ExternalProcess.Run` is `async`, you'd need (AFAIK) to `await` it, calling `.Result` directly leads to all kinds of problems. Which means the `async` keyword will need to propagate a bit up the call stack.

**Comment by sharpSteff** [comment]
@skolima calling .Result is indeed a blocking call, but in this case there should be no problems.

However a better approach as you mentioned, to include `async`

**Comment by sharpSteff** [comment]
@skolima managed to get rid of the `.Result`.

Also added some unit tests.
I still have to check whether everything runs also on Linux.
And in addition I have to finish the `GitDiscoveryDriver `

**Comment by MarcBruins** [comment]
There are still merge conflicts can you check them? Are you also confident that this works now?

**Comment by sharpSteff** [comment]
@MarcBruins 
there are still 2 open points:

-  update docu
-  The IGitDiscoveryDriver is currently as a singleton implemented. Any ideas to inject dynamically the GitCmdDiscoveryDriver, when the command line is applied.

**Comment by sharpSteff** [comment]
updated docu

**Comment by sharpSteff** [comment]
@MarcBruins I'm confident everything works. We're already running our nukeeper on windows with git cli (repo/update) commands. I tested everything as well on Ubuntu. Also I added unit tests to be sure.

**Comment by Chama-StephanTuinder** [comment]
Would be nice to see a full-implementation of the GitCmdDriver.

**Comment by StephanTuinder** [comment]
Would be nice to see a full-implementation of the GitCmdDriver.

**Comment by sharpSteff** [comment]
@StephanTuinder 
What additional Features are needed ?

**Comment by StephanTuinder** [comment]
Weird, in my mind there where a lot of NotImplemented routines. Probably my branch was behind.

**Comment by sharpSteff** [comment]
Never mind!

Great that you find that issue in GitCmdDiscoveryDriver. I'll take a look at the tests

**Comment by StephanTuinder** [comment]
I fixed it in my PR, so check there

**Pull request merged**
