### PR TITLE
Bump version in Dockerfile to 0.35.0

### PR DESCRIPTION
**Pull request by skolima**
Update to current release in the Dockerfiles provided.

### CODE REVIEW

**Comment by msallin** [comment]
Is this necessary, can't we just use the latest?

**Comment by skolima** [comment]
Problem with having `latest` in there is that the Docker images aren't deterministic then.

And building them becomes problematic, as it's either "invalidate every time and build from scratch" or "we'll get whatever is cached on the build machine, perhaps the current version, perhaps 3 versions stale".

**Comment by msallin** [comment]
I see. How do we release a new NuKeeper version? Maybe we can automate this.
I'm working on getting a bit of dev power from our organization, to do such things.

**Review by msallin — APPROVED** [review]

**Comment by skolima** [comment]
There's a (somewhat grotty) Azure Devops pipeline. It's not the most readable, TBH. I'd prefer GitHub actions, or really anything that's versioned in the repository as a text file. The Docker images used to be released automatically by Docker Hub - but now they've changed their licensing, there's no longer a free build tier for Open Source - so the last ones was built on my machine. That could also move to GitHub Actions - there's free automation here for it.

**Pull request merged**
