### PR TITLE
Add TFS support

### PR DESCRIPTION
**Pull request by shep1987**
Add support for TFS for https://github.com/NuKeeperDotNet/NuKeeper/issues/532

I dislike the code in `AzureDevOpsRepositoryDiscovery` but is the only way i can get it to work until https://github.com/libgit2/libgit2sharp/issues/1596 is fixed

### CODE REVIEW

**Comment by MarcBruins** [comment]
LGTM

**Comment by MustafaJamal** [comment]
Hi @shep1987, we checked that still we are facing issue mentioned here:
https://github.com/libgit2/libgit2sharp/issues/1596

**Comment by zplan** [comment]
is there any progress reagarding this issue?

**Comment by shep1987** [comment]
As the source issue is not resolved im afraid not.

**Pull request merged**
