### PR TITLE
[Azure Devops] Auto complete support

### PR DESCRIPTION
**Pull request by Berreek**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature.

### :arrow_heading_down: What is the current behavior?
Cannot mark PR as autocompleted.

### :new: What is the new behavior (if this is a feature change)?
Can mark PR as autocompleted by using new configuration parameter (setautocomplete) in repo command.

### :boom: Does this PR introduce a breaking change?
No, parameter is optional and set to false on default.

### :bug: Recommendations for testing
N/A

### :memo: Links to relevant issues/docs
https://github.com/NuKeeperDotNet/NuKeeper/issues/938

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Relevant documentation was updated

### CODE REVIEW

**Comment by jozefchmelar** [comment]
Thank you for your code @Berreek ! I used it in my fork and it works perfectly.

**Comment by Berreek** [comment]
@skolima Any update for it?

**Comment by skolima** [comment]
Could you update from master so that this branch builds, please? I'm also not sold on the naming - it's specific to Azure, while adding a general option.  Azure calls this "set auto-complete" flag https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops while GitHub (and Dependabot) call this auto-merging ( https://github.com/dependabot/feedback/issues/954 ) and that's naming I'm more familiar with.

What would you say about naming the option `setautomergeflag`? (docs updated accordingly once we settle on a name).

@AnthonySteele could you perhaps comment?

**Comment by Berreek** [comment]
I updated the branch.

Regarding the name - I called it auto-complete beacuse I looked only on Azure to be honest. I agree with you that auto-merge will get better understanding since complete is Azure specific as you said. 

Let me know if we stick with it.

**Comment by Berreek** [comment]
@skolima I renamed the option from `setautocomplete` to `setautomerge` - is there something else that need to be done in order to merge that PR?

**Comment by ykysel** [comment]
@Berreek @skolima do you have any ETA for this? It will be very helpful

**Comment by skolima** [comment]
Truth be told, I don't think any of the original developers uses NuKeeper any more. But I'll try to find time to release this.

**Pull request merged**
