### PR TITLE
#798 Respect Platform argument

### PR DESCRIPTION
**Pull request by msallin**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix.

### :arrow_heading_down: What is the current behavior?
Platform argument is not respected.

### :new: What is the new behavior (if this is a feature change)?
Platform argument is respected.

### :boom: Does this PR introduce a breaking change?
Maybe. If someone passes a platform argument, which is not respected and the platform argument does not correspond to the platform which is currently inferred from the URI, this change will be breaking.

### :bug: Recommendations for testing
I tested only with BitbucketLocal and did no regressions tests.

### :memo: Links to relevant issues/docs
#798 

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Relevant documentation was updated

### CODE REVIEW

**Comment by shep1987** [comment]
Hey @msallin,

As this is a draft still did you need some help with this? 

Looks to me like this is close would be great to add a test to make sure you have fixed the issue!

Thanks

Shaun

**Comment by msallin** [comment]
Due to an infrastructur issue I was not able to test until now.
The fix works with BitbucketLocal, I added a test and filled out the required information in the PR description.

**Comment by shep1987** [comment]
No worries, we all get busy! thank you for your time.

There unfortunately seems to be merge conflicts now are you ok fixing these or did you need some help?

**Comment by msallin** [comment]
Here we go.

**Comment by msallin** [comment]
@shep1987 is there something I need to do, to get this PR merged?

**Comment by shep1987** [comment]
Sorry was at sisters wedding and then have just completed on a house so busy few weeks this all looks good thanks for the work!

**Pull request merged**
