### PR TITLE
Fixes local source path escaping

### PR DESCRIPTION
**Pull request by skolima**

### CODE REVIEW

**Comment by skolima** [comment]
Related to #386

**Comment by AnthonySteele** [comment]
`ArgumentEscaper.EscapeAndConcatenate` looks useful, but what is actually going wrong with adding `"` quotes? Are some of the args already `IsSurroundedWithQuotes` ?

**Comment by skolima** [comment]
I was adding a) quotes where they weren't required (see the updated test - there's no need to quote the first source) and b) not escaping the `/` where it was required (thus the source `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\` was failing. CMD.exe is odd in that `\` only needs to be escaped sometimes. Fun!

**Comment by AnthonySteele** [comment]
Ah, so _a_ was not fatal but _b_ was. Well spotted! and good that someone already has code to do the right thing with it!

**Pull request merged**
