### PR TITLE
SDK version 2.1.507

### PR DESCRIPTION
**Pull request by skolima**
Current LTS security update

### CODE REVIEW

**Comment by skolima** [comment]
Travis doesn't have 2.1.507 available yet - need to re-check soon.

**Comment by skolima** [comment]
Regarding travis, this is the output when installing dotnet-sdk-2.1:

```
Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240
.NET Core SDKs installed:
  2.1.604 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
0.01s$ dotnet build -c Release NuKeeper.sln /m:1
A compatible SDK version for global.json version: [2.1.507] from [/home/travis/build/skolima/NuKeeper/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Seems like 2.1.507 isn't there, but newer release is. It makes sense, I guess - 2.1.507 is mostly a cludge for VS 2017. I'm thinking if perhaps we should drop the global.json and move to 2.2 SDK for building? The result will still run on 2.1 runtime if we keep it as a target.

**Comment by MaxMommersteeg** [comment]
I think it would be good to build with the 2.2 SDK. As you said, we can still target the 2.1 runtime.

**Comment by skolima** [comment]
replaced by #796

**Pull request closed without merging**
