### PR TITLE
[Bitbucket Local] Add new API call to get the current BitBucket Server user details

### PR DESCRIPTION
**Pull request by KeyDecoder**
This adds a new API call for BitBucket Server (local) to get the user details from the username provided to use in creating a valid git user for the platform if possible.

Changed GetCurrentUser to use the actual user details if they can be read out instead of username and empty email which was causing it to always revert to using the git config

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Enhancement to use the user details from the user provided for BitBucket Server integration.

### :arrow_heading_down: What is the current behavior?

Currently only provides the username when creating a user for a commit signature, but this fails (since no name or email) and falls back to using the git config.

### :new: What is the new behavior (if this is a feature change)?

It will now attempt to lookup the user in BitBucket to get the name and email. If it cannot find the user, it will still fallback to the existing behaviour.

### :boom: Does this PR introduce a breaking change?

This will break any integrations which rely on it using the git config for the user that creates the commits and if this user is different to the username provided in the command line.

No impact on any other integrations or BitBucket Cloud.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Relevant documentation was updated

### CODE REVIEW

**Comment by KeyDecoder** [comment]
Implements #973

**Comment by KeyDecoder** [comment]
Hi @AnthonySteele and other maintainers, what is the best way to progress this?  I'm not sure if have any BitBucket Local specific developers who should review this.

**Comment by KeyDecoder** [comment]
Add a check to resolve an issue where libgit2 was creating symbolic links and it was causing issues in test cleanup where tests did a checkout and tried to clean up.

**Comment by skolima** [comment]
For the libgit2 issue, after confirming with @AnthonySteele , I've upgraded to the preview version which doesn't have the bug. So we don't need the workaround in this ticket.

As for BitBucket maintenance/features, @MarcBruins could you perhaps take a look please?

**Pull request closed without merging**
