### PR TITLE
easyconfig configuration error handling to handle missing arguments

### PR DESCRIPTION
**Pull request by cohen990**
The error handling will end up with a throw (and a dotnet core crash)

If that's acceptable to us, then easyconfig already has code in place for informative error handling (even if the elegance of it is questionable)

example

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Perhas that should have a `try...catch(ConfigurationException) {}` in the program to output the exception message and exit(1) ?  Other than that, I am ok with it.

**Comment by skolima** [comment]
As long as those messages are informative, I'm ok with this. Just no `IndexOutOfBounds` or other built-in exceptions.

**Comment by cohen990** [comment]
@skolima the attached image details the type of error I'm talking about. There may still be edge cases that I've not considered (I'm sure there are) but they need to be fixed in EasyConfig, not compensated for in NuKeeper

**Comment by AnthonySteele** [comment]
👍 Looks ok to me. Is it ready to merge?

**Comment by cohen990** [comment]
It is now @AnthonySteele

**Pull request merged**
