### PR TITLE
Maxupdate has 0 option to allow all

### PR DESCRIPTION
**Pull request by MarcBruins**
For a project that i've been working on i use the following command:

`nukeeper update --include ^EventSourcing. --age 0 --maxupdate 50`

This yields about 50 packages update in total. 7 project with about 7 `EventSourcing.*` packages. It would be nice to just say `--maxupdate 0` and allow it to update as many as it wants.

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Should we use a nullable `int?` for this?

**Comment by MarcBruins** [comment]
So then the default if not `1` anymore but always max?

**Comment by MarcBruins** [comment]
Can you elaborate your comment @AnthonySteele and answer my question?

**Comment by AnthonySteele** [comment]
It should fail safe, i.e. to a small number. 
Can you not  use a larger limit, `500` or `10000` if you want no effective limit?

**Comment by MarcBruins** [comment]
Yes that is what we do now. But that isn't a very nice solution imo. We just want it to update the whole project and we don't know how many updates it has. 

If we could pass in `0` we can always cancel it by just pressing ctrl+c. That is a rather abrupt stop and it doesn't revert changes but we don't care cause we can just revert the changes with git.

In the end it's effectively the same as passing in `500` or `10000` but just a cleaner solution.

**Comment by AnthonySteele** [comment]
We have used `--maxpr 0` to mean "zero updates" so it would be odd to make `0` mean "all the updates" in a different context.

**Comment by MaxMommersteeg** [comment]
Why not allow a set of strings for input? "max" or "all" could be used for all the updates. "none" could be an alias to 0. Uints could easily be parsed.

**Comment by MarcBruins** [comment]
Good suggestion @MaxMommersteeg, i'll look into that.

**Pull request closed without merging**
