### PR TITLE
Moving to CommandLineUtils

### PR DESCRIPTION
**Pull request by skolima**
Exploring options for #323 

Status:
- [x] `inspect` starts
- [x] `inspect` accepts options and help
- [x] logging levels can be set
- [x] `update` command works
- [x] `repository` command works
- [x] `organisation` command works
- [ ] TODO: various smaller configuration settings
- [ ] documentation update
- [ ] version output correct

This would not include configuration file support.

### CODE REVIEW

**Comment by skolima** [comment]
image

**Comment by AnthonySteele** [comment]
Allowed change should not show the `None` member of that enum.

**Comment by skolima** [comment]
Verbosity settings would now look like this (syntax snatched from `dotnet`):

image

@AnthonySteele could you have a look later at https://github.com/NuKeeperDotNet/NuKeeper/pull/324/commits/e44817a90990572d0107fb753f77561d7f99532a and tell me what you think? I had to make the logger mutable, but that is hidden by an explicit interface implementation.

**Comment by AnthonySteele** [comment]
Ready to merge?

**Comment by skolima** [comment]
I'd say it's ready now. I'll add the "TODO" checklist on the Issue itself.

**Pull request merged**
