### PR TITLE
Configurable auto deletion of branch after merge.

### PR DESCRIPTION
**Pull request by MaxMommersteeg**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature.

### :arrow_heading_down: What is the current behavior?
Azure DevOps branches get automatically deleted after merge. This behavior can be altered with this pull request.
This pr allows Gitlab  branches to be automatically deleted aswell. There currently is a different pull request that allows for automatic deletion of source branches after merge for Gitlab: https://github.com/NuKeeperDotNet/NuKeeper/pull/773

### :new: What is the new behavior (if this is a feature change)?
Automatic deletion of source branches (for Azure DevOps and Gitlab) after merge can now be altered. 

### :boom: Does this PR introduce a breaking change?
Azure DevOps branches get automatically deleted after merge. This pr changes the default, branches will not be deleted automatically afterwards for both platforms (Azure DevOps and Gitlab).

### :bug: Recommendations for testing
Test on Azure DevOps and Gitlab repositories with outdated packages.

### :memo: Links to relevant issues/docs
Configuration page of docs has been updated.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Relevant documentation was updated

### CODE REVIEW

**Comment by MaxMommersteeg** [comment]
This PR now contains all functionality that https://github.com/NuKeeperDotNet/NuKeeper/pull/773 adds and more by allowing deletion of source branch to be configurable. Defaults have been changed to `true` for this setting.

**Comment by MaxMommersteeg** [comment]
PR now also contains all functionality of https://github.com/NuKeeperDotNet/NuKeeper/pull/788.

**Comment by MarcBruins** [comment]
Can have a look at the conflicts?

**Comment by MaxMommersteeg** [comment]
Merge conflicts are resolved.

**Comment by MarcBruins** [comment]
LGTM

**Pull request merged**
