### PR TITLE
Fix target-branch for azure devops client.

### PR DESCRIPTION
**Pull request by kwlin**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Fix target-branch for Azure DevOps client. It seems the PR #1074 isn't sufficient enough for Azure DevOps after testing.  @CrispyDrone 

### :arrow_heading_down: What is the current behavior?
After providing the targetbranch argument, NuKeeper keep checking against the default branch of the repo.

### :new: What is the new behavior (if this is a feature change)?
Fix the PR #1074 

### :boom: Does this PR introduce a breaking change?
nop

### :bug: Recommendations for testing
Provide the --targetBranch argument against the Azure DevOps repo and see that NuKeeper will check dependencies against the provided --targetBranch.

### :memo: Links to relevant issues/docs
-

### :thinking: Checklist before submitting

- [ ] All projects build
- [x] Relevant documentation was updated 
- [x] Unit tests added

### CODE REVIEW

**Comment by kwlin** [comment]
After reviewing the class I saw something strange in the method ["CreateSettingsFromLocal"](https://github.com/NuKeeperDotNet/NuKeeper/blob/65166412508b25579cec3fadfe0a5c5cabe85bde/NuKeeper.AzureDevOps/AzureDevOpsSettingsReader.cs#L100). There is a variable remoteInfo instantiated but never used. 

It seems to be refactored during this PR #841. I'm not sure if we should provide the remoteinfo variable to the method "CreateRepositorySettings"

Any ideas?

**Comment by kwlin** [comment]
And any ideas how I can fix the builds to finish this PR. TIA :)

**Comment by MarcBruins** [comment]
@CrispyDrone can you confirm that this adds to your PR? And maybe review this one?

**Comment by CrispyDrone** [comment]
@kwlin @MarcBruins 

I only have an Azure Devops _Server_ instance at work, so unfortunately I cannot test it very easily there. I do have a personal azure devops service instance that I could try out. I'll give it a try.

**Comment by kwlin** [comment]
@CrispyDrone thanks for verifying my changes. I have tested my changes against Azure DevOps but not against Azure Devops Server Instance ;)

Any pointers how I can fix the builds?

**Comment by kwlin** [comment]
@CrispyDrone any help needed for completing this PR?

**Comment by CrispyDrone** [comment]
Hello @kwlin 

At work we've actually migrated to the cloud version of Azure Devops so I stumbled upon this issue (as well as many others).

I'm in the process of implementing fixes in my own fork.

**Comment by CrispyDrone** [comment]
I think this fix is missing a change in the `PackageUpdater`. Have a look at this commit: https://github.com/CrispyDrone/NuKeeper/commit/10d8cf1f8424fde471b6ffdf968226297fc0caf0

**Comment by kwlin** [comment]
@CrispyDrone  sorry for the delay in reply (was very busy lately). Anyway thanks for the additional fix and I'm curious about other issues you have found :) 

I can apply the change in the PR but I'm not sure what the PackageUpdater class does.

**Review by MartinDemberger — APPROVED** [review]

**Comment by kwlin** [comment]
@skolima  Could you review this PR also? I'm tagging you because of your great work of merging my PR's 😄

**Comment by skolima** [comment]
Yeah, that looks ok.

**Pull request merged**
