### PR TITLE
In Verbose mode, report git fetch progress every 10%

### PR DESCRIPTION
**Pull request by skolima**

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Some git operations would be faster if we didn't have to get full history - "shallow clone"
Unfortunately the underlying git lib doesn't  support that.

**Comment by cohen990** [comment]
Is the underlying git library open source?

**Comment by skolima** [comment]
https://github.com/libgit2/libgit2sharp

**Comment by AnthonySteele** [comment]
https://github.com/libgit2/libgit2sharp/issues/229

**Pull request merged**
