### PR TITLE
[Bitbucket] Adding reviewers to pull request

### PR DESCRIPTION
**Pull request by danielmedina**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
When it creates a pull request in bitbucket, it doesn't add any reviewer. So, nobody is notified when there is a new pull request.

### :new: What is the new behavior (if this is a feature change)?
In this commit I implemented add repository's default reviewers as reviewers of the created pull request. The default reviewers will be added unless the user is the same that want to create the pull request.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
N/A

### :memo: Links to relevant issues/docs
N/A

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Relevant documentation was updated

### CODE REVIEW

**Comment by MarcBruins** [comment]
Can we add a test for this?

**Comment by danielmedina** [comment]
I can try, but I don't know where to start 🤣

**Comment by danielmedina** [comment]
@AnthonySteele or anybody else could help me? Idk why these two jobs are failing. Is it anything about my code? Or about your environment?

**Comment by KeyDecoder** [comment]
@danielmedina I've fixed an issue with Windows builds in my [pull request](https://github.com/NuKeeperDotNet/NuKeeper/pull/974) and there is a fix in the [TestDirectoryHelper.cs](https://github.com/NuKeeperDotNet/NuKeeper/pull/974/files#diff-d10e544bcf9c04caaeee7652dd0b3ed9) and while I cannot see your previous build run I assume it is probably the same issue.

**Pull request closed without merging**
