### PR TITLE
Setup code coverage

### PR DESCRIPTION
**Pull request by zubivan**
This PR uses coverlet (https://github.com/tonerdo/coverlet) for code coverage.

- [x] Collect code coverage during the build pipeline run
- [x] Upload and store results

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Nice! What does the coverlet output look like?

**Comment by zubivan** [comment]
Example output for Nukeeper.Tests project:

```
  Generating report '/Users/Ivan/Source/NuKeeper/NuKeeper.Tests/coverage.json'

+-------------------------+-------+--------+--------+
| Module                  | Line  | Branch | Method |
+-------------------------+-------+--------+--------+
| NuKeeper.BitBucketLocal | 0%    | 0%     | 0%     |
+-------------------------+-------+--------+--------+
| NuKeeper.Inspection     | 31.2% | 20%    | 37.3%  |
+-------------------------+-------+--------+--------+
| NuKeeper.BitBucket      | 0%    | 0%     | 0%     |
+-------------------------+-------+--------+--------+
| NuKeeper.Update         | 28.4% | 16.4%  | 42.2%  |
+-------------------------+-------+--------+--------+
| NuKeeper.AzureDevOps    | 7%    | 0.6%   | 4.2%   |
+-------------------------+-------+--------+--------+
| NuKeeper                | 90.5% | 87.8%  | 97%    |
+-------------------------+-------+--------+--------+
| NuKeeper.Abstractions   | 61.4% | 45.7%  | 71%    |
+-------------------------+-------+--------+--------+
| NuKeeper.GitHub         | 18.6% | 4.5%   | 22%    |
+-------------------------+-------+--------+--------+
| NuKeeper.Git            | 10.3% | 10.5%  | 10%    |
+-------------------------+-------+--------+--------+
| NuKeeper.Gitlab         | 0%    | 0%     | 0%     |
+-------------------------+-------+--------+--------+
| NuKeeper.Tests          | 99.9% | 98%    | 99.6%  |
+-------------------------+-------+--------+--------+

+---------+-------------------+-------------------+--------+
|         | Line              | Branch            | Method |
+---------+-------------------+-------------------+--------+
| Total   | 57.8%             | 34.7%             | 41.8%  |
+---------+-------------------+-------------------+--------+
| Average | 5.25454545454545% | 3.15454545454545% | 3.8%   |
+---------+-------------------+-------------------+--------+


Total tests: 43. Passed: 43. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 20.9667 Seconds
```

And that's the raw output:
https://gist.github.com/zubivan/1fb8ad5a54856275e6e43e1e58b0c41e

**Comment by AnthonySteele** [comment]
Those are about the levels that I expected :(

I have seen very nice graphical output, e.g. [with codecov here](https://codecov.io/gh/justeat/JustEat.StatsD) or [as described here](https://medium.com/bluekiri/code-coverage-in-vsts-with-xunit-coverlet-and-reportgenerator-be2a64cd9c2f)

**Comment by zubivan** [comment]
That’s exactly what I’m aiming at. That’s the kind of graphical output we can get with coverall:
https://coveralls.io/github/gitlabhq/gitlabhq

**Comment by zubivan** [comment]
And we got the collection in.
image

Needs some extra configuration on the azure side to configure the pretty view.

**Pull request merged**
