### PR TITLE
Just ask directly for files we're interested in.

### PR DESCRIPTION
**Pull request by skolima**
No need to enumerate the whole directory.

I realised I'll need to re-do this on once #28 is merged.

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Fair enough, but we should merge #28 first

**Comment by cohen990** [comment]
like both of you have said, this needs to be re-done :P

**Comment by skolima** [comment]
Re-done on latest master

**Comment by AnthonySteele** [comment]
👍

**Pull request merged**
