### PR TITLE
Add Yml file

### PR DESCRIPTION
**Pull request by shep1987**
Add the build config for Azure DevOps as a yml file. Meaning build config can be version controlled and reviewed before changes.

### CODE REVIEW

**Comment by MarcBruins** [comment]
Why do we do a publish here?

**Comment by shep1987** [comment]
image


> Why do we do a publish here?

image
This is the same as we do in the current release. Instead of having 2 configs one for PR and one for Master this just allows us to only publish if the branch being built is master (Via a manual trigger)

**Comment by AnthonySteele** [comment]
it's really nice to to have the pipeline config as a file under source control.
There is also benefit of having 2 different flows for branch build and for a release from master.
But this can be done with a conditional step?

**Comment by MarcBruins** [comment]
:shipit:

**Pull request merged**
