### PR TITLE
Trying out mixing command line git and LibGit2SharpDriver

### PR DESCRIPTION
**Pull request by skolima**

### CODE REVIEW

**Comment by skolima** [comment]
Limitation: quite sure this will break (hang) when working with a git clone not created by NuKeeper and requiring password authentication. I'm open to suggestions how best to handle this - thinking about detecting this somehow and keeping `libgitsharp` in those cases.

**Comment by skolima** [comment]
So, on any issues with the command, this hangs indefinitely. Not ideal.

**Comment by MarcBruins** [comment]
Can we make this works for the local version first and then focus on the extra cloning steps? Would be very helpful to have this for a local `nukeeper repo {pat} ./` command. Why would it hang indefinitely? Could we read stdout and check for failures?

**Comment by shep1987** [comment]
As #800 got merge can this be closed now?

**Comment by skolima** [comment]
obsolete

**Pull request closed without merging**
